# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SmartLink Mirror' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SmartLink Mirror
  target 'SmartLink MirrorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartLink MirrorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
